In [15]:
import numpy as np

In [16]:
a = np.array([[1,2,3],
              [4,5,6]])
a.shape

(2, 3)

In [17]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [18]:
a[0]

np.int64(1)

In [19]:
type(a[1])

numpy.int64

In [20]:
a[3]

np.int64(4)

In [21]:
a[1]=10
a

array([ 1, 10,  3,  4,  5])

In [22]:
a[0:6]

array([ 1, 10,  3,  4,  5])

In [23]:
b = a[3:]
b[0]=40
a

array([ 1, 10,  3, 40,  5])

In [24]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
a[0,3]=20
a

array([[ 1,  2,  3, 20],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
a[2,2]

np.int64(11)

### Array attributes

In [27]:
a.ndim

2

In [28]:
a.shape

(3, 4)

In [29]:
len(a.shape)!=a.ndim

False

In [30]:
a.size

12

In [31]:
import math
a.size==math.prod(a.shape)

True

### How to create a basic array

In [32]:
np.empty(2)

array([0., 0.])

In [33]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [34]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [35]:
np.linspace(2.5,10,num=5)

array([ 2.5  ,  4.375,  6.25 ,  8.125, 10.   ])

In [36]:
x=np.ones(2,dtype=np.int64)
x

array([1, 1])

### Adding,removing, and sorting elements

In [37]:
arr=np.array([34,1,0,45,2,9])
np.sort(arr)

array([ 0,  1,  2,  9, 34, 45])

In [38]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
x = np.array([[1, 2,5], [3, 4,8]])
y = np.array([[5, 6,10]])

In [40]:
np.concatenate((x, y), axis=0)

array([[ 1,  2,  5],
       [ 3,  4,  8],
       [ 5,  6, 10]])

In [41]:
array_example=np.array([[[0,1,2,3],[4,5,6,7]],
                        [[10,11,12,13],[14,15,16,17]],
                        [[18,19,20,21],[22,23,24,25]]])

In [42]:
array_example

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[10, 11, 12, 13],
        [14, 15, 16, 17]],

       [[18, 19, 20, 21],
        [22, 23, 24, 25]]])

In [43]:
array_example.ndim

3

In [44]:
array_example.size

24

In [45]:
array_example.shape

(3, 2, 4)

### Can you reshape an array ?


In [46]:
a = np.arange(9)
print(a)

[0 1 2 3 4 5 6 7 8]


In [47]:
b=a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
np.reshape(a,shape=(1,9),order='C')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

How to convert a 1D array into a 2D array(how to add a new axis to an array)

In [49]:
a = np.arange(7)
a

array([0, 1, 2, 3, 4, 5, 6])

In [50]:
a2=a[np.newaxis,:]
a2.shape

(1, 7)

In [51]:
row_vector=a[np.newaxis,:]
row_vector.shape

(1, 7)

In [52]:
col_vector=a[:,np.newaxis]
col_vector.shape

(7, 1)

In [53]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [54]:
b=np.expand_dims(a,axis=1)
b.shape

(6, 1)

In [55]:
c=np.expand_dims(a,axis=0)
c.shape

(1, 6)

### Indexing and slicing

In [56]:
data=np.array([1,2,3])
data[0:1]

array([1])

In [57]:
data[-2:]

array([2, 3])

In [58]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a.shape

(4, 3)

In [59]:
print(a[a<5])

[1 2 3 4]


In [60]:
a[a>=5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [61]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [62]:
a[a%3==0]

array([ 3,  6,  9, 12])

In [63]:
c=a[(a>2)&(a<11)]
c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
a[(a>5)|(a==5)]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [65]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
b=np.nonzero(a<5)
b

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

In [67]:
list_of_coordinates=list(zip(b[0],b[1]))

for coord in list_of_coordinates:
    print(coord)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))


In [68]:
print(a[b])

[1 2 3 4]


In [69]:
not_there=np.nonzero(a==42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


#### How to create an array from existing data

In [70]:
a = np.array([1,2,3,4,5,6,7,8,9,10]) 

In [71]:
arr=a[3:8]
arr

array([4, 5, 6, 7, 8])

In [72]:
a1=np.array([[1,1],
             [2,2]])
a2=np.array([[3,3],
             [4,4]])

In [73]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [74]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [75]:
x=np.arange(1,25).reshape(2,12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [76]:
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [77]:
np.hsplit(x,(3,4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [78]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [79]:
b1=a[0,:]
b1

array([1, 2, 3, 4])

In [80]:
b1[0]=99
b1

array([99,  2,  3,  4])

In [81]:
a


array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [82]:
b2=a.copy()

b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Basic array operations

In [83]:
data=np.array([1,2])
ones=np.ones(2,dtype=int)
data+ones

array([2, 3])

In [84]:
data/data

array([1., 1.])

In [85]:
a=np.array([1,2,3,4])
a.sum()

np.int64(10)

In [86]:
b = np.array([[1,1],[2,2]])

In [87]:
b.sum(axis=1)

array([2, 4])

### BroadCasting

In [88]:
data=np.array([1.0,2.0])
data * 1.6

array([1.6, 3.2])

### More useful array operations


In [89]:
data.min()

np.float64(1.0)

In [90]:
data.max()

np.float64(2.0)

In [91]:
data.mean()

np.float64(1.5)

In [92]:
a=np.random.randint(1,100,50)
a

array([92, 21,  9, 99, 76, 97, 53, 44, 36,  6, 42, 74, 28,  7, 10, 97, 76,
       53, 83, 44, 11, 32, 34, 91, 73, 96, 14, 68, 10, 24,  2, 82, 86, 47,
       31, 96, 99, 75, 19, 87, 36, 33, 88, 48,  3, 23, 37, 22, 97, 75],
      dtype=int32)

In [93]:
a.sum()

np.int64(2586)

In [94]:
a.min()

np.int32(2)

In [95]:
a.max()

np.int32(99)

In [96]:
a.meanZ()

AttributeError: 'numpy.ndarray' object has no attribute 'meanZ'

In [ ]:
a.mean()

np.float64(52.7)

In [ ]:
a.min(axis=0)

np.int32(1)

### Creating Matrices

In [ ]:
data=np.array([[[1,2],[3,4],[5,6]]])
data

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [ ]:
data = np.array([[1,2],[5,3],[4,6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [ ]:
data.max(axis=0)

array([5, 6])

In [ ]:
data.max(axis=1)

array([2, 5, 6])

In [ ]:
data=np.array([[1,2],[3,4]])
ones=np.array([[1,1],[1,1]])
data+ones

array([[2, 3],
       [4, 5]])

In [ ]:
data=np.array([[1,2],[3,4],[5,6]])
ones_row=np.array([[1,1]])
data+ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
np.ones(3)


array([1., 1., 1.])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
rng=np.random.default_rng()
rng.random(3)

array([0.12798808, 0.75622918, 0.98021089])

In [ ]:
np.random((3,2))

TypeError: 'module' object is not callable

In [ ]:
rng=np.random.default_rng()
rng.random(3)

array([0.48757248, 0.10043098, 0.89429703])

### Generating random numbers

In [ ]:
rng.integers(5,size=(2,4))

array([[4, 2, 1, 3],
       [4, 3, 4, 3]])

In [ ]:
import numpy as np

### How to get unique items and counts

In [ ]:
a = np.array([11,11,12,13,14,12,15,16,17,18,20,20])

In [ ]:
unique_values=np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 20]


In [ ]:
unique_values,indices_list=np.unique(a,return_index=True)
print(indices_list)

[ 0  2  3  4  6  7  8  9 10]


In [ ]:
unique_values,occurance_count=np.unique(a,return_counts=True)
print(occurance_count)

[2 2 1 1 1 1 1 1 2]


In [ ]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [ ]:
unique_values=np.unique(a_2d)
unique_values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
unique_rows=np.unique(a_2d,axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
unique_rows,indices,occurance_count=np.unique(
    a_2d,axis=0,return_counts=True,return_index=True
)

In [ ]:
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(indices)

[0 1 2]


In [ ]:
print(occurance_count)

[2 1 1]


### Tranposing and reshaping a matrix

In [98]:
data.reshape(2,3)

ValueError: cannot reshape array of size 2 into shape (2,3)

In [99]:
arr = np.arange(6).reshape((2,3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [100]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

### How to reverse an array

In [102]:
arr=np.arange(9)
reversed_arr=np.flip(arr)
reversed_arr

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

In [103]:
arr=np.arange(16).reshape(4,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [104]:
reversed_arr=np.flip(arr)
reversed_arr

array([[15, 14, 13, 12],
       [11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

In [ ]:
reversed_arr=np.flip(arr,axis=1) # it is columns
reversed_arr # when axis = 1

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12]])

In [109]:
reversed_arr=np.flip(arr,axis=0)
reversed_arr

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [110]:
x=np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [111]:
x.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [112]:
a2=x.ravel()
a2[0]=98
x

array([[98,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [113]:
print(a2)

[98  1  2  3  4  5  6  7  8  9 10 11]
